### ISSUE TITLE
Not possible to require module because release version is mission.

### ISSUE THREAD

**Issue by BorisovskiP** [Leankoala/HealthFoundation#4]
Its not possible to require the module with composer because there is no release version specified. 

When calling `composer require leankoala/healthfoundation ` the following error it thrown: 

` [InvalidArgumentException]                                                                                                                                                       
  Could not find a version of package leankoala/healthfoundation matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired st  
  ability. `

**Comment by phmLabs** [comment]
Released v1.0.0
